version: '3'

services:
    php-cli:
        tty: true
        build:
            context: ./php/cli
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        command: php -r "while (true) { sleep(86400); }"
        restart: always
        working_dir: /var/www/html/facebook-simple-authentication
        volumes:
            - ./../../facebook-simple-authentication:/var/www/html/facebook-simple-authentication:rw
            - ./php/dev-php.ini:/usr/local/etc/php/php.ini:ro

    php-fpm:
        build:
            context: ./php/fpm
        restart: on-failure
        environment:
            PHP_IDE_CONFIG: serverName=Docker
        volumes:
            - ./../../facebook-simple-authentication:/var/www/html/facebook-simple-authentication:rw
            - ./php/dev-php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/fpm/dev-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        depends_on:
            - php-cli

    nginx:
        image: nginx:1.21
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - php-fpm
        volumes:
            - ./../../facebook-simple-authentication:/var/www/html/facebook-simple-authentication:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:ro
            # Warning! ssl must be located on host machine
            - ./nginx/certs:/etc/nginx/ssl:ro
        restart: on-failure
